/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import config.Conexion;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Universidad
 */
public class frmLogin extends javax.swing.JFrame {
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;

    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        cboType.addItem("Seleccione");
        cboType.addItem("Rector");
        cboType.addItem("Profesor");
        cboType.addItem("Estudiante");
    }

    public void limpiar_cajas() {
        txtpwd.setText("");
        cboType.setSelectedItem("Seleccione");
        txtUser.requestFocus();
    }

    public void validar_usuario() {
        
        int resultado = 0;
        String pass = String.valueOf(txtpwd.getPassword());
        String usuario = txtUser.getText();
        String tipo = App.tipo_usuario;
        String SQL = "SELECT * FROM usuarios WHERE usuario='" + usuario + "' and pass='" + pass + "' and rol='" + tipo + "'";

        try {
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(SQL);

            if (rs.next()) {
                resultado = 1;
                if (resultado == 1) {
                    frmPrincipal ppal = new frmPrincipal();
                    ppal.setLocationRelativeTo(null);
                    ppal.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error de Acceso, Usuario No Registrado");
            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFirma = new javax.swing.JPanel();
        lblFirma = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        lblpwd = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();
        cboType = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO DE SESION - v1.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFirma.setBackground(new java.awt.Color(255, 255, 255));

        lblFirma.setFont(new java.awt.Font("Roboto Black", 2, 10)); // NOI18N
        lblFirma.setForeground(new java.awt.Color(102, 102, 102));
        lblFirma.setText("Daniel Almanza ©");

        javax.swing.GroupLayout pnlFirmaLayout = new javax.swing.GroupLayout(pnlFirma);
        pnlFirma.setLayout(pnlFirmaLayout);
        pnlFirmaLayout.setHorizontalGroup(
            pnlFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFirmaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblFirma)
                .addContainerGap())
        );
        pnlFirmaLayout.setVerticalGroup(
            pnlFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFirmaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFirma))
        );

        getContentPane().add(pnlFirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 490, 100, 10));

        lblTitle.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("EDUSENA");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, 90));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoSenaPequeno.png"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        lblUser.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 204, 204));
        lblUser.setText("USUARIO");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 480, 30));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(51, 51, 51));
        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, 20));

        lblpwd.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        lblpwd.setForeground(new java.awt.Color(204, 204, 204));
        lblpwd.setText("CONTRASEÑA");
        getContentPane().add(lblpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        txtpwd.setBackground(new java.awt.Color(255, 255, 255));
        txtpwd.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtpwd.setForeground(new java.awt.Color(51, 51, 51));
        txtpwd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 140, 20));

        cboType.setBackground(new java.awt.Color(51, 51, 51));
        cboType.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        cboType.setForeground(new java.awt.Color(255, 255, 255));
        cboType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        getContentPane().add(cboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 120, -1));

        btnIngresar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 480, -1));

        background.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        background.setForeground(new java.awt.Color(51, 51, 51));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String usuario = txtUser.getText();
        String pass = new String(txtpwd.getPassword());

        if (usuario.equals("") || pass.equals("") || cboType.getSelectedItem().equals("Seleccione")) {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtUser.requestFocus();
        } else if(cboType.getSelectedItem().equals("Rector")){
            App.tipo_usuario = "Rector";
            validar_usuario();
            limpiar_cajas();
        } else if (cboType.getSelectedItem().equals("Profesor")) {
            App.tipo_usuario = "Profesor";
            validar_usuario();
            limpiar_cajas();
        } else if (cboType.getSelectedItem().equals("Estudiante")) {
            App.tipo_usuario ="Estudiante";
            validar_usuario();
            limpiar_cajas();
            
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JLabel icon;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFirma;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblpwd;
    private javax.swing.JPanel pnlFirma;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPasswordField txtpwd;
    // End of variables declaration//GEN-END:variables
}
